### ISSUE TITLE
no hugo extended pre-compiled as mentionned

### ISSUE THREAD

**Issue by JOduMonT** [christoph-cullmann/cullmann.io#10]
;)
hi;
so I found your repo via your post about hugo on centos
https://cullmann.io/posts/hugo-extended-centos-7/

which you offer a link to this repo by mentioning you have a precompiled version

where it is ?? :)

**Comment by christoph-cullmann** [comment]
At the moment I don't use that anymore, but if you look in the history of this repo, you should find a binary.

(toplevel, e.g. in https://github.com/christoph-cullmann/cullmann.io/tree/457e894d357b15aa7a0eb1e72bb4921cdc591e9c)
